//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommonFiles.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All check box is not displayed.
        /// </summary>
        public static string AllCheckBoxNotDisp {
            get {
                return ResourceManager.GetString("AllCheckBoxNotDisp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given Batch number and Status is not matched..
        /// </summary>
        public static string BatchNoAndStatusNotMatch {
            get {
                return ResourceManager.GetString("BatchNoAndStatusNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Batch Table view is not displayed.
        /// </summary>
        public static string BatchTableViewNotDisp {
            get {
                return ResourceManager.GetString("BatchTableViewNotDisp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm message box is not displayed..
        /// </summary>
        public static string ConfirmMessageError {
            get {
                return ResourceManager.GetString("ConfirmMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Batch button is not displayed.
        /// </summary>
        public static string CreateBatchBtnNotDisp {
            get {
                return ResourceManager.GetString("CreateBatchBtnNotDisp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create batch page is not displayed..
        /// </summary>
        public static string CreateBatchPageError {
            get {
                return ResourceManager.GetString("CreateBatchPageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Due Table grid is not displayed..
        /// </summary>
        public static string CurrentTableGridNotDisp {
            get {
                return ResourceManager.GetString("CurrentTableGridNotDisp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given CW number and Weekending date not matched..
        /// </summary>
        public static string CwNumberWeekendNotMatch {
            get {
                return ResourceManager.GetString("CwNumberWeekendNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Microsoft Office Access database engine cannot open or write to the file . It is already opened exclusively by another user, or you need permission to view and write its data.
        /// </summary>
        public static string FileAlreadyUsed {
            get {
                return ResourceManager.GetString("FileAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given Batch Number is not selected..
        /// </summary>
        public static string GivenBchNumNotSecleted {
            get {
                return ResourceManager.GetString("GivenBchNumNotSecleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given Voucher number is not paid or some problem occured.
        /// </summary>
        public static string GivenVoucherNotPaid {
            get {
                return ResourceManager.GetString("GivenVoucherNotPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next button is not displayed..
        /// </summary>
        public static string NextBtnNotDisp {
            get {
                return ResourceManager.GetString("NextBtnNotDisp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No batch records find for given batch number.
        /// </summary>
        public static string NoBatchRecordsWithGivenBatchNO {
            get {
                return ResourceManager.GetString("NoBatchRecordsWithGivenBatchNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records find for given CW number.
        /// </summary>
        public static string NoRecordswithcwno {
            get {
                return ResourceManager.GetString("NoRecordswithcwno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PA Number is not displayed..
        /// </summary>
        public static string PaNumberNotDisp {
            get {
                return ResourceManager.GetString("PaNumberNotDisp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Batch number is empty.
        /// </summary>
        public static string SearchBatchEmpty {
            get {
                return ResourceManager.GetString("SearchBatchEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search CW number is empty.
        /// </summary>
        public static string SearchCwNumberEmpty {
            get {
                return ResourceManager.GetString("SearchCwNumberEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the Created batch number.
        /// </summary>
        public static string UnabletoCreateBatch {
            get {
                return ResourceManager.GetString("UnabletoCreateBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given Voucher number is paid by Approver successfully done.
        /// </summary>
        public static string VocPaidByApprover {
            get {
                return ResourceManager.GetString("VocPaidByApprover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given voucher number and Status is not matched..
        /// </summary>
        public static string VoucherNumberNotMached {
            get {
                return ResourceManager.GetString("VoucherNumberNotMached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher Number is not genarated..
        /// </summary>
        public static string VoucherNumNotGen {
            get {
                return ResourceManager.GetString("VoucherNumNotGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vouchers created Successfully done.
        /// </summary>
        public static string VouchersCreateSuccess {
            get {
                return ResourceManager.GetString("VouchersCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher Table View is not displayed..
        /// </summary>
        public static string VoucherTableViewNotDisp {
            get {
                return ResourceManager.GetString("VoucherTableViewNotDisp", resourceCulture);
            }
        }
    }
}
